//! Binary-column export and bounded preview support.
//!
//! SQL Server's `binary`, `varbinary`, and legacy `image` types are user BLOB
//! data. `rowversion` and its deprecated `timestamp` synonym are deliberately
//! rejected: their eight bytes are generated by SQL Server as concurrency
//! tokens, not user-owned file content.

use base64::Engine as _;
use mssql_tiberius_bridge::ToSql;

use crate::driver::helpers::{bracket_quote, build_pk_where_clause, qualify, value_to_sql_param};
use crate::driver::{acquire, introspection};
use crate::models::{ConnectionParams, PkMap};

/// Matches Tabularis' host-side default. Newer hosts may forward their
/// configured `max_blob_size` with the preview request; older hosts omit it.
pub const DEFAULT_MAX_BLOB_SIZE: u64 = 100 * 1024 * 1024;

pub async fn fetch_blob_bytes(
    params: &ConnectionParams,
    table: &str,
    col_name: &str,
    pk_map: &PkMap,
    schema: Option<&str>,
    max_preview_size: Option<u64>,
) -> Result<Vec<u8>, String> {
    let mut conn = acquire(params).await?;
    let columns = introspection::get_columns(&mut conn, table, schema).await?;
    let column = columns
        .iter()
        .find(|column| column.name == col_name)
        .ok_or_else(|| {
            format!(
                "SQL Server BLOB column {}.{} was not found",
                qualify(schema, table),
                bracket_quote(col_name)
            )
        })?;
    validate_blob_data_type(&column.data_type)?;

    let mut primary_keys: Vec<_> = pk_map.iter().collect();
    primary_keys.sort_by_key(|&(column, _)| column);
    let pk_columns: Vec<String> = primary_keys
        .iter()
        .map(|(column, _)| (*column).clone())
        .collect();
    let first_pk_marker = if max_preview_size.is_some() { 2 } else { 1 };
    let predicate = build_pk_where_clause(&pk_columns, first_pk_marker).ok_or_else(|| {
        "SQL Server: BLOB lookup requires at least one primary-key column".to_string()
    })?;

    let mut owned_params: Vec<Box<dyn ToSql>> = Vec::with_capacity(primary_keys.len() + 1);
    let sql = if let Some(max_size) = max_preview_size {
        let sql_limit = i64::try_from(max_size).unwrap_or(i64::MAX);
        owned_params.push(Box::new(sql_limit));
        format!(
            "SELECT CAST(DATALENGTH({column}) AS BIGINT), \
             CASE WHEN CAST(DATALENGTH({column}) AS BIGINT) <= @P1 \
                  THEN CONVERT(VARBINARY(MAX), {column}) END \
             FROM {table} WHERE {predicate}",
            column = bracket_quote(col_name),
            table = qualify(schema, table),
        )
    } else {
        format!(
            "SELECT CONVERT(VARBINARY(MAX), {}) FROM {} WHERE {}",
            bracket_quote(col_name),
            qualify(schema, table),
            predicate,
        )
    };

    for (_, value) in primary_keys {
        owned_params.push(value_to_sql_param(value)?);
    }
    let bound: Vec<&dyn ToSql> = owned_params.iter().map(|value| value.as_ref()).collect();
    let rows = conn
        .query(sql, &bound)
        .await
        .map_err(|error| format!("Failed to fetch SQL Server BLOB: {error}"))?
        .into_first_result();
    let row = rows
        .first()
        .ok_or_else(|| "SQL Server BLOB row was not found".to_string())?;

    if let Some(max_size) = max_preview_size {
        let size = row
            .try_get::<i64, _>(0)
            .map_err(|error| format!("Failed to read SQL Server BLOB size: {error}"))?
            .ok_or_else(|| "SQL Server BLOB value is NULL".to_string())?;
        let size = u64::try_from(size)
            .map_err(|_| format!("SQL Server returned an invalid BLOB size: {size}"))?;
        ensure_preview_size(size, max_size)?;
        return row
            .try_get::<&[u8], _>(1)
            .map_err(|error| format!("Failed to read SQL Server BLOB value: {error}"))?
            .map(<[u8]>::to_vec)
            .ok_or_else(|| "SQL Server BLOB value is NULL".to_string());
    }

    row.try_get::<&[u8], _>(0)
        .map_err(|error| format!("Failed to read SQL Server BLOB value: {error}"))?
        .map(<[u8]>::to_vec)
        .ok_or_else(|| "SQL Server BLOB value is NULL".to_string())
}

pub fn encode_blob_full(data: &[u8], max_preview_size: u64) -> Result<String, String> {
    ensure_preview_size(data.len() as u64, max_preview_size)?;
    let mime_type = infer::get(data)
        .map(|kind| kind.mime_type())
        .unwrap_or("application/octet-stream");
    let encoded = base64::engine::general_purpose::STANDARD.encode(data);
    Ok(format!("BLOB:{}:{mime_type}:{encoded}", data.len()))
}

/// Decode the internal BLOB value sent back by the host during row editing.
/// Returns `Ok(None)` for ordinary strings so callers can bind them as text.
pub fn decode_blob_wire(value: &str) -> Result<Option<Vec<u8>>, String> {
    if !value.starts_with("BLOB:") {
        return Ok(None);
    }
    let mut fields = value.splitn(4, ':');
    let _prefix = fields.next();
    let declared_size = fields
        .next()
        .and_then(|size| size.parse::<usize>().ok())
        .ok_or_else(|| "SQL Server BLOB value has an invalid size".to_string())?;
    let _mime_type = fields
        .next()
        .filter(|mime| !mime.is_empty())
        .ok_or_else(|| "SQL Server BLOB value has an empty MIME type".to_string())?;
    let payload = fields
        .next()
        .ok_or_else(|| "SQL Server BLOB value has no base64 payload".to_string())?;
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(payload)
        .map_err(|error| format!("SQL Server BLOB value has invalid base64: {error}"))?;
    if bytes.len() != declared_size {
        return Err(format!(
            "SQL Server BLOB value declares {declared_size} bytes but contains {} bytes",
            bytes.len()
        ));
    }
    Ok(Some(bytes))
}

pub fn validate_writable_file_path(file_path: &str) -> Result<(), String> {
    if file_path.trim().is_empty() {
        return Err("file_path must not be empty".to_string());
    }
    let path = std::path::Path::new(file_path);
    if path.is_dir() {
        return Err(format!(
            "file_path '{file_path}' is a directory, not a file"
        ));
    }
    match path.parent() {
        Some(parent) if !parent.as_os_str().is_empty() && !parent.is_dir() => Err(format!(
            "file_path '{file_path}': parent directory '{}' does not exist",
            parent.display()
        )),
        _ => Ok(()),
    }
}

fn ensure_preview_size(size: u64, max_preview_size: u64) -> Result<(), String> {
    if size > max_preview_size {
        return Err(format!(
            "SQL Server BLOB preview is {size} bytes, exceeding max_blob_size of \
             {max_preview_size} bytes; export the value to a file instead"
        ));
    }
    Ok(())
}

fn validate_blob_data_type(data_type: &str) -> Result<(), String> {
    let normalized = data_type.trim().to_ascii_uppercase();
    let base_type = normalized.split('(').next().unwrap_or(normalized.as_str());
    match base_type {
        "BINARY" | "VARBINARY" | "IMAGE" => Ok(()),
        "ROWVERSION" | "TIMESTAMP" => Err(format!(
            "SQL Server {base_type} is a server-generated concurrency token, not user BLOB data"
        )),
        _ => Err(format!(
            "SQL Server column type {data_type} is not supported for BLOB export or preview"
        )),
    }
}

#[cfg(test)]
#[path = "blob/tests.rs"]
mod tests;
